/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poo.uva.a4petcare;

/**
 *
 * @author vieir
 */
public class LogadoMain extends javax.swing.JFrame {

    /**
     * Creates new form LogadoMain
     */
    public LogadoMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgendarCon = new javax.swing.JButton();
        btnConsultarAg = new javax.swing.JButton();
        btnCadastrarCli = new javax.swing.JButton();
        btnCadastrarUsu = new javax.swing.JButton();
        btnRealizarCon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");

        btnAgendarCon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAgendarCon.setText("AGENDAR CONSULTA");
        btnAgendarCon.setName(""); // NOI18N
        btnAgendarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarConActionPerformed(evt);
            }
        });

        btnConsultarAg.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConsultarAg.setText("CONSULTAR AGENDA");
        btnConsultarAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAgActionPerformed(evt);
            }
        });

        btnCadastrarCli.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastrarCli.setText("CADASTRAR CLIENTE");
        btnCadastrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCliActionPerformed(evt);
            }
        });

        btnCadastrarUsu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastrarUsu.setText("CADASTRAR USUÁRIO");
        btnCadastrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuActionPerformed(evt);
            }
        });

        btnRealizarCon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRealizarCon.setText("REALIZAR CONSULTA");
        btnRealizarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarConActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("MENU DE ATIVIDADES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCadastrarUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultarAg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgendarCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRealizarCon, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnAgendarCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRealizarCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarAg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarUsu)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCliActionPerformed
        // TODO add your handling code here:
        CadastroPetFrame Main = new CadastroPetFrame();
        Main.setVisible(true);
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarCliActionPerformed

    private void btnCadastrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuActionPerformed
        // TODO add your handling code here:
        CadastroUsuarioFrame Main = new CadastroUsuarioFrame();
        Main.setVisible(true);
        //this.setVisible(false);
        this.dispose(); 
    }//GEN-LAST:event_btnCadastrarUsuActionPerformed

    private void btnRealizarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarConActionPerformed
        // TODO add your handling code here:
        AtendimentoFrame Main = new AtendimentoFrame();
        Main.setVisible(true);
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnRealizarConActionPerformed

    private void btnAgendarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarConActionPerformed
        AgendamentoFrame Main = new AgendamentoFrame();
        Main.setVisible(true);
        //this.setVisible(false);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgendarConActionPerformed

    private void btnConsultarAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAgActionPerformed
        // TODO add your handling code here:
        CaonsultarAgendaFrame Main = new CaonsultarAgendaFrame();
        Main.setVisible(true);
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnConsultarAgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogadoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogadoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogadoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogadoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogadoMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarCon;
    private javax.swing.JButton btnCadastrarCli;
    private javax.swing.JButton btnCadastrarUsu;
    private javax.swing.JButton btnConsultarAg;
    private javax.swing.JButton btnRealizarCon;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
